# Generated by Django 3.1.10 on 2023-01-01 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='publish',
        ),
    ]
