# Generated by Django 2.2 on 2023-01-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='second_status',
            field=models.CharField(blank=True, choices=[('SE', 'مشاهده شده'), ('DG', 'در حال انجام'), ('WG', 'در انتظار قطعه'), ('ST', 'ارسال به پیمانکار'), ('DN', 'تکمیل شده')], max_length=2, null=True),
        ),
    ]
