# Generated by Django 3.1.10 on 2023-01-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_order_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
