# Generated by Django 4.1.4 on 2023-01-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_repairoperator_task_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='second_status',
            field=models.CharField(blank=True, choices=[('SE', 'مشاهده شده'), ('DG', 'دز حال انجام'), ('WG', 'در انتظار قطعه'), ('ST', 'ارسال به پیمانکار'), ('DN', 'تکمیل شده')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('SE', 'مشاهده شده'), ('DG', 'دز حال انجام'), ('WG', 'در انتظار قطعه'), ('ST', 'ارسال به پیمانکار'), ('DN', 'تکمیل شده')], max_length=2, null=True),
        ),
    ]
