# Generated by Django 4.1.4 on 2022-12-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_order_unique_together_order_today_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='today',
            field=models.DateField(auto_now_add=True),
        ),
    ]
