# Generated by Django 4.1.4 on 2022-12-21 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_order_today'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
