# Generated by Django 4.1.4 on 2022-12-21 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_order_unique_together_alter_order_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='today',
            field=models.DateField(default=datetime.datetime(2022, 12, 21, 13, 46, 50, 283176, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('today', 'operation')},
        ),
    ]
