# Generated by Django 4.1.4 on 2022-12-21 13:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_unique_together_alter_order_operation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='today',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.operation'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('today', 'operation')},
        ),
    ]
