# Generated by Django 4.1.4 on 2022-12-25 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order_today_alter_order_operation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='base.operation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='base.order'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('today', 'operation', 'description')},
        ),
    ]
