# Generated by Django 4.1.4 on 2022-12-31 18:01

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_task_options_alter_order_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
