# Generated by Django 4.1.4 on 2022-12-31 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_order_managers_order_publish_task_publish'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
            ],
        ),
    ]
